services:
  - type: web
    name: filmatch-backend
    runtime: node
    buildCommand: cd backend && npm install
    startCommand: node backend/server.js
    envVars:
      - key: TMDB_API_KEY
        sync: false
      - key: RAPIDAPI_KEY
        sync: false
      - key: GROQ_API_KEY
        sync: false
      - key: PORT
        value: 10000
